build_mau:
  outputs:
    dev:
      account: DDTFIEU-FKB21226
      database: DEV
      password: Bharathy@sjsu25
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: BHARATHYKUMAR
      warehouse: COMPUTE_WH
  target: dev
lab2_dbt:
  outputs:
    dev:
      account: DDTFIEU-FKB21226
      database: dev
      password: Bharathy@sjsu25
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: BHARATHYKUMAR
      warehouse: compute_wh
  target: dev
tesla_project:
  outputs:
    dev:
      account: OWEEGXT-GVB74384
      database: DEV
      password: Bharathy@sjsu25
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: BHARATHYKUMAR
      warehouse: COMPUTE_WH
  target: dev
